<a href="https://colab.research.google.com/github/zrtashi/AI/blob/Ai/RealEstate_Data_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Wrangling Data**

In [7]:
!git add notebook_name.ipynb
!git commit -m "RealEstate_Data_Wrangling.ipynb"
!git push origin main

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

In [6]:
!sudo apt-get install git

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.11).
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.

In [ ]:
# Import libraries
import matplotlib.pyplot as plt
import pandas as pd
import plotly.express as px

In [ ]:
df=pd.read_csv('/content/data.csv')

In [ ]:
df.head()

,Location,Area,Baths,Beds,Dining Room,Laundry Room,Store Rooms,Kitchens,Drawing Room,Gym,Powder Room,Steam Room,No additional rooms,Prayer Rooms,Lounge or Sitting Room,Price
0,"Bahria Town, Lahore, Punjab",10 Marla,-,-,0,0,0,0,0,0,0,0,1,0,0,PKR3.5 Crore
1,"Al Rehman Garden, Lahore, Punjab",4 Marla,4,3,1,1,1,2,1,0,0,0,0,1,0,PKR1.32 Crore
2,"Central Park Housing Scheme, Lahore, Punjab",5 Marla,4,3,0,0,0,0,0,0,0,0,1,0,0,PKR1.74 Crore
3,"DHA Defence, Lahore, Punjab",1 Kanal,6,5,0,0,0,0,0,0,0,0,0,0,0,PKR10.3 Crore
4,"DHA Defence, Lahore, Punjab",1 Kanal,6,5,1,1,2,2,1,0,1,1,0,1,1,PKR8.25 Crore

In [ ]:
df.shape

(7500, 16)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Location                7500 non-null   object
 1   Area                    7500 non-null   object
 2   Baths                   7500 non-null   object
 3   Beds                    7500 non-null   object
 4   Dining Room             7500 non-null   int64
 5   Laundry Room            7500 non-null   int64
 6   Store Rooms             7500 non-null   int64
 7   Kitchens                7500 non-null   int64
 8   Drawing Room            7500 non-null   int64
 9   Gym                     7500 non-null   int64
 10  Powder Room             7500 non-null   int64
 11  Steam Room              7500 non-null   int64
 12  No additional rooms     7500 non-null   int64
 13  Prayer Rooms            7500 non-null   int64
 14  Lounge or Sitting Room  7500 non-null   int64
 15  Price                   7500 non-null   object
dtypes: int64(11), object(5)
memory usage: 937.6+ KB

In [ ]:
df["Price"].head(10)

0     PKR3.5 Crore
1    PKR1.32 Crore
2    PKR1.74 Crore
3    PKR10.3 Crore
4    PKR8.25 Crore
5      PKR15 Crore
6       PKR85 Lakh
7       PKR63 Lakh
8     PKR8.9 Crore
9      PKR17 Crore
Name: Price, dtype: object

## Make a function to remove "PKR" prefix and convert Price in numerical values

In [ ]:


def convert_price(price_str):
    # Remove 'PKR' prefix
    price_str = price_str.replace("PKR", "").strip()

    # Convert Crore to numerical value
    if "Crore" in price_str:
        price_str = price_str.replace("Crore", "").strip()
        return float(price_str) * 1e7  # 1 Crore = 10 million (1e7)

    # Convert Lakh to numerical value
    elif "Lakh" in price_str:
        price_str = price_str.replace("Lakh", "").strip()
        return float(price_str) * 1e5  # 1 Lakh = 100 thousand (1e5)

    return None  # In case the format is unexpected

# Apply the conversion to the Price column
df["Price"] = df["Price"].apply(convert_price)

print(df)

                                         Location       Area Baths Beds  \
0                     Bahria Town, Lahore, Punjab   10 Marla     -    -
1                Al Rehman Garden, Lahore, Punjab    4 Marla     4    3
2     Central Park Housing Scheme, Lahore, Punjab    5 Marla     4    3
3                     DHA Defence, Lahore, Punjab    1 Kanal     6    5
4                     DHA Defence, Lahore, Punjab    1 Kanal     6    5
...                                           ...        ...   ...  ...
7495     Top City 1, Islamabad, Islamabad Capital   10 Marla     -    -
7496     Top City 1, Islamabad, Islamabad Capital    1 Kanal     -    -
7497     Top City 1, Islamabad, Islamabad Capital   10 Marla     -    -
7498    Mumtaz City, Islamabad, Islamabad Capital  6.7 Marla     -    -
7499     Top City 1, Islamabad, Islamabad Capital   10 Marla     -    -

      Dining Room  Laundry Room  Store Rooms  Kitchens  Drawing Room  Gym  \
0               0             0            0         0             0    0
1               1             1            1         2             1    0
2               0             0            0         0             0    0
3               0             0            0         0             0    0
4               1             1            2         2             1    0
...           ...           ...          ...       ...           ...  ...
7495            1             1            0         0             1    1
7496            1             1            0         0             1    1
7497            1             1            0         0             1    1
7498            1             1            0         0             1    1
7499            1             1            0         0             1    1

      Powder Room  Steam Room  No additional rooms  Prayer Rooms  \
0               0           0                    1             0
1               0           0                    0             1
2               0           0                    1             0
3               0           0                    0             0
4               1           1                    0             1
...           ...         ...                  ...           ...
7495            1           1                    0             1
7496            1           1                    0             1
7497            1           1                    0             1
7498            1           1                    0             1
7499            1           1                    0             1

      Lounge or Sitting Room        Price
0                          0   35000000.0
1                          0   13200000.0
2                          0   17400000.0
3                          0  103000000.0
4                          1   82500000.0
...                      ...          ...
7495                       1   40000000.0
7496                       1   42000000.0
7497                       1   40000000.0
7498                       1   25000000.0
7499                       1   50000000.0

[7500 rows x 16 columns]

In [ ]:
df["Price"].head()

0     35000000.0
1     13200000.0
2     17400000.0
3    103000000.0
4     82500000.0
Name: Price, dtype: float64

# **Change Price column name **

In [ ]:
# Rename the 'Price' column to 'Price_Rs'
df.rename(columns={"Price": "Price_Rs"}, inplace=True)

In [ ]:
df.head()

,Location,Area,Baths,Beds,Dining Room,Laundry Room,Store Rooms,Kitchens,Drawing Room,Gym,Powder Room,Steam Room,No additional rooms,Prayer Rooms,Lounge or Sitting Room,Price_Rs
0,"Bahria Town, Lahore, Punjab",10 Marla,-,-,0,0,0,0,0,0,0,0,1,0,0,35000000.0
1,"Al Rehman Garden, Lahore, Punjab",4 Marla,4,3,1,1,1,2,1,0,0,0,0,1,0,13200000.0
2,"Central Park Housing Scheme, Lahore, Punjab",5 Marla,4,3,0,0,0,0,0,0,0,0,1,0,0,17400000.0
3,"DHA Defence, Lahore, Punjab",1 Kanal,6,5,0,0,0,0,0,0,0,0,0,0,0,103000000.0
4,"DHA Defence, Lahore, Punjab",1 Kanal,6,5,1,1,2,2,1,0,1,1,0,1,1,82500000.0

In [ ]:
df["Area"].head(10)

0    10 Marla
1     4 Marla
2     5 Marla
3     1 Kanal
4     1 Kanal
5     2 Kanal
6     4 Marla
7     5 Marla
8    17 Marla
9     2 Kanal
Name: Area, dtype: object

# **Convert Kanal into Marla**

In [ ]:

# Conversion function
def convert_area(area):
    if 'Kanal' in area:
        num = float(area.split()[0])
        return f"{num * 20} Marla"
    return area

# Apply the conversion function to the 'Area' column
df['Area'] = df['Area'].apply(convert_area)

# Display the updated DataFrame
print(df)

                                         Location        Area Baths Beds  \
0                     Bahria Town, Lahore, Punjab    10 Marla     -    -
1                Al Rehman Garden, Lahore, Punjab     4 Marla     4    3
2     Central Park Housing Scheme, Lahore, Punjab     5 Marla     4    3
3                     DHA Defence, Lahore, Punjab  20.0 Marla     6    5
4                     DHA Defence, Lahore, Punjab  20.0 Marla     6    5
...                                           ...         ...   ...  ...
7495     Top City 1, Islamabad, Islamabad Capital    10 Marla     -    -
7496     Top City 1, Islamabad, Islamabad Capital  20.0 Marla     -    -
7497     Top City 1, Islamabad, Islamabad Capital    10 Marla     -    -
7498    Mumtaz City, Islamabad, Islamabad Capital   6.7 Marla     -    -
7499     Top City 1, Islamabad, Islamabad Capital    10 Marla     -    -

      Dining Room  Laundry Room  Store Rooms  Kitchens  Drawing Room  Gym  \
0               0             0            0         0             0    0
1               1             1            1         2             1    0
2               0             0            0         0             0    0
3               0             0            0         0             0    0
4               1             1            2         2             1    0
...           ...           ...          ...       ...           ...  ...
7495            1             1            0         0             1    1
7496            1             1            0         0             1    1
7497            1             1            0         0             1    1
7498            1             1            0         0             1    1
7499            1             1            0         0             1    1

      Powder Room  Steam Room  No additional rooms  Prayer Rooms  \
0               0           0                    1             0
1               0           0                    0             1
2               0           0                    1             0
3               0           0                    0             0
4               1           1                    0             1
...           ...         ...                  ...           ...
7495            1           1                    0             1
7496            1           1                    0             1
7497            1           1                    0             1
7498            1           1                    0             1
7499            1           1                    0             1

      Lounge or Sitting Room     Price_Rs
0                          0   35000000.0
1                          0   13200000.0
2                          0   17400000.0
3                          0  103000000.0
4                          1   82500000.0
...                      ...          ...
7495                       1   40000000.0
7496                       1   42000000.0
7497                       1   40000000.0
7498                       1   25000000.0
7499                       1   50000000.0

[7500 rows x 16 columns]

In [ ]:
df.head(10)

,Location,Area,Baths,Beds,Dining Room,Laundry Room,Store Rooms,Kitchens,Drawing Room,Gym,Powder Room,Steam Room,No additional rooms,Prayer Rooms,Lounge or Sitting Room,Price_Rs
0,"Bahria Town, Lahore, Punjab",10 Marla,-,-,0,0,0,0,0,0,0,0,1,0,0,35000000.0
1,"Al Rehman Garden, Lahore, Punjab",4 Marla,4,3,1,1,1,2,1,0,0,0,0,1,0,13200000.0
2,"Central Park Housing Scheme, Lahore, Punjab",5 Marla,4,3,0,0,0,0,0,0,0,0,1,0,0,17400000.0
3,"DHA Defence, Lahore, Punjab",20.0 Marla,6,5,0,0,0,0,0,0,0,0,0,0,0,103000000.0
4,"DHA Defence, Lahore, Punjab",20.0 Marla,6,5,1,1,2,2,1,0,1,1,0,1,1,82500000.0
5,"DHA Defence, Lahore, Punjab",40.0 Marla,6,5,1,1,1,2,1,0,1,1,0,1,1,150000000.0
6,"Kahna, Lahore, Punjab",4 Marla,4,4,1,0,1,2,1,0,0,0,0,0,0,8500000.0
7,"Kahna, Lahore, Punjab",5 Marla,3,2,1,0,1,1,1,0,1,0,0,0,0,6300000.0
8,"Askari, Lahore, Punjab",17 Marla,6,5,1,0,1,2,1,0,1,0,0,0,1,89000000.0
9,"Valencia Housing Society, Lahore, Punjab",40.0 Marla,6,6,1,1,0,0,1,0,1,1,0,1,1,170000000.0

# Remove Marla from Area column

In [ ]:
# Remove 'PKR' suffix
df["Area"] = df["Area"].str.replace("Marla", "", regex=False)

In [ ]:
# changle name Area to "Area[Marla]"
df.rename(columns={"Area": "Area[Marla]"}, inplace=True)

In [ ]:
df

,Location,Area[Marla],Baths,Beds,Dining Room,Laundry Room,Store Rooms,Kitchens,Drawing Room,Gym,Powder Room,Steam Room,No additional rooms,Prayer Rooms,Lounge or Sitting Room,Price_Rs
0,"Bahria Town, Lahore, Punjab",10,-,-,0,0,0,0,0,0,0,0,1,0,0,35000000.0
1,"Al Rehman Garden, Lahore, Punjab",4,4,3,1,1,1,2,1,0,0,0,0,1,0,13200000.0
2,"Central Park Housing Scheme, Lahore, Punjab",5,4,3,0,0,0,0,0,0,0,0,1,0,0,17400000.0
3,"DHA Defence, Lahore, Punjab",20.0,6,5,0,0,0,0,0,0,0,0,0,0,0,103000000.0
4,"DHA Defence, Lahore, Punjab",20.0,6,5,1,1,2,2,1,0,1,1,0,1,1,82500000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,"Top City 1, Islamabad, Islamabad Capital",10,-,-,1,1,0,0,1,1,1,1,0,1,1,40000000.0
7496,"Top City 1, Islamabad, Islamabad Capital",20.0,-,-,1,1,0,0,1,1,1,1,0,1,1,42000000.0
7497,"Top City 1, Islamabad, Islamabad Capital",10,-,-,1,1,0,0,1,1,1,1,0,1,1,40000000.0
7498,"Mumtaz City, Islamabad, Islamabad Capital",6.7,-,-,1,1,0,0,1,1,1,1,0,1,1,25000000.0
7499,"Top City 1, Islamabad, Islamabad Capital",10,-,-,1,1,0,0,1,1,1,1,0,1,1,50000000.0

# **Now delete irrelevant columns**

In [ ]:
#delete irrelevant columns
df.drop(columns = ["Laundry Room", "Gym", "Powder Room", "Steam Room", "No additional rooms","Prayer Rooms"], inplace=True)

In [ ]:
df.head()

,Location,Area[Marla],Baths,Beds,Dining Room,Store Rooms,Kitchens,Drawing Room,Lounge or Sitting Room,Price_Rs
0,"Bahria Town, Lahore, Punjab",10,-,-,0,0,0,0,0,35000000.0
1,"Al Rehman Garden, Lahore, Punjab",4,4,3,1,1,2,1,0,13200000.0
2,"Central Park Housing Scheme, Lahore, Punjab",5,4,3,0,0,0,0,0,17400000.0
3,"DHA Defence, Lahore, Punjab",20.0,6,5,0,0,0,0,0,103000000.0
4,"DHA Defence, Lahore, Punjab",20.0,6,5,1,2,2,1,1,82500000.0